### PR TITLE
Add CLI Version Flag

### PR DESCRIPTION
**Pull request by lindgrenj6**
I added a version flag because you release every 10 seconds or so. Would be nice to be able to see if I'm out of date or not.

### CODE REVIEW

**Comment by mschneider82** [comment]
Hi, 
Thanks for your PR.

Do you use the .deb or .rpm package? You could check the version with `dpkg -l sharecmd` or `rpm -qa sharecmd`

I dont want to update the source with the versions tag every time, I have to find another way to include the `--version` number with the automated goreleaser build.

**Comment by mschneider82** [comment]
and sorry for the release flood, i was tring to get ubuntus `snap` working. but my snap support it still buggy.

**Comment by lindgrenj6** [comment]
Oh it's no problem!

I installed with `go get -u` so I don't have a version number, that is the only reason I added it. In your script you could have a sed command that replaces version upon build? That would be one way to do it. I'll add another commit to this if you would like me to do it.

**Comment by mschneider82** [comment]
--version/-v tag added with goreleaser auto overwrite. Unfortunately its not set when you compile the version by yourself unless you do `go build -ldflags "-X main.version=0.0.75"`

In your commit kingpin.Arg was wrong, i changed it to Flag

**Pull request closed without merging**
